イベントのサンプルを追加
inc-brick/Medici pull request #77
Opened 2020-02-08 08:32 UTC by corentytakeshi

次回リリースでMediciにイベントを追加する
それに伴い、画面にイベント項目の追加

画像をクリックするとイベントのサイトに遷移する

2020-02-08 13:21 UTC, takithon requested changes

2020-02-08 13:21 UTC, kennyTakimura commented on front/src/presentations/components/EventView.vue
> +        　<a :href="event.eventUrl">
イベントのページは新規タブで開かなくていいですか？

2020-02-08 18:49 UTC, corentytakeshi commented
@kennyTakimura 
コメントありがとう！
新規タブで開きたいので、修正しました

2020-02-12 14:54 UTC, kennyTakimura commented on front/src/presentations/components/EventView.vue
> +        　<a :href="event.eventUrl">
@corentytakeshi 
閉じます

2020-02-12 14:55 UTC, merged